# Generated by Django 3.2.7 on 2021-09-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_music_audio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='time_length',
        ),
    ]
